### ISSUE TITLE
这个项目有6个小的路径错误的地方，造成拉下来后运行报错，是运行不起来项目的

### ISSUE THREAD

**Issue by juqingzhenfuza** [meiwen520gmx/react-admin#1]
![71602580007_ pic_hd](https://user-images.githubusercontent.com/27800396/95841058-80511980-0d77-11eb-806e-cff51fb68fab.jpg)

**Comment by MandiGao** [comment]
这个问题已解决，由于components文件夹下有些组件下的Index是大写，有些是小写index,上传git时出现了问题，导致引入发生错误，感谢您指出问题。以后还请多多交流。
![image](https://user-images.githubusercontent.com/40172690/95867817-257de900-0d9c-11eb-9378-77fd081dd01c.png)

**Comment by juqingzhenfuza** [comment]
> 这个问题已解决，由于components文件夹下有些组件下的Index是大写，有些是小写index,上传git时出现了问题，导致引入发生错误，感谢您指出问题。以后还请多多交流。
> ![image](https://user-images.githubusercontent.com/40172690/95867817-257de900-0d9c-11eb-9378-77fd081dd01

**Comment by juqingzhenfuza** [comment]
我对react是小白，只不过以前用的vue，这个项目页面东西比是很多但是写的还特别清晰，适合react初学者学习，以后还需要您多多指教。
